import { MembershipTier, WorkshopTypes } from "./types";

export const TIERS: MembershipTier[] = [
  {
    id: "free",
    name: "Free",
    price: 0,
    badge: "Starter",
    badgeColor: "bg-purple-100 text-purple-700",
    tagline: "Explore the community at no cost.",
    accentColor: "border-purple-950/10",
    cardBg: "bg-white",
    buttonStyle:
      "border border-purple-950/20 text-purple-950 hover:bg-purple-50",
    popular: false,
    features: [
      "Browse all public campaigns",
      "Read community forums",
      "Monthly iLEAD newsletter",
      "Public event announcements",
      "View iTrain previews",
    ],
    locked: [
      "Join & comment on campaigns",
      "Mentorship matching",
      "iShare participation",
      "Certificate of contribution",
      "Priority support",
    ],
  },
  {
    id: "silver",
    name: "Silver",
    price: 2500,
    badge: "Community",
    badgeColor: "bg-slate-100 text-slate-600",
    tagline: "Get active in the iLEAD ecosystem.",
    accentColor: "border-slate-300",
    cardBg: "bg-white",
    buttonStyle: "border border-slate-400 text-slate-700 hover:bg-slate-50",
    popular: false,
    features: [
      "Everything in Free",
      "Join & comment on campaigns",
      "Full community forum access",
      "Basic iTrain content library",
      "Priority email support",
      "Member directory listing",
    ],
    locked: [
      "Mentorship matching",
      "iShare participation",
      "Certificate of contribution",
      "Leadership direct access",
    ],
  },
  {
    id: "gold",
    name: "Gold",
    price: 5000,
    badge: "Most Popular",
    badgeColor: "bg-orange-100 text-orange-700",
    tagline: "Unlock mentorship, sharing, and growth.",
    accentColor: "border-orange-400",
    cardBg: "bg-white",
    buttonStyle:
      "bg-orange-500 hover:bg-orange-600 text-white shadow-md shadow-orange-500/20",
    popular: true,
    features: [
      "Everything in Silver",
      "Mentorship matching (2 sessions/mo)",
      "iShare participation — give & receive",
      "Full iTrain content library",
      "Certificate of contribution",
      "Top Givers leaderboard eligibility",
    ],
    locked: [
      "Unlimited mentorship sessions",
      "Featured profile badge",
      "Direct leadership access",
    ],
  },
  {
    id: "platinum",
    name: "Platinum",
    price: 10000,
    badge: "Premium",
    badgeColor: "bg-purple-950 text-white",
    tagline: "The full iLEAD experience, no limits.",
    accentColor: "border-purple-950",
    cardBg: "bg-white",
    buttonStyle:
      "bg-purple-950 hover:bg-purple-800 text-white shadow-md shadow-purple-950/20",
    popular: false,
    features: [
      "Everything in Gold",
      "Unlimited mentorship sessions",
      "Featured profile & verification badge",
      "Direct access to iLEAD leadership",
      "Early access to new features",
      "Custom community spotlight post",
      "Dedicated account support",
    ],
    locked: [],
  },
];

export const workshops: WorkshopTypes[] = [
  {
    id: "1",
    title: "CGPA Planning & Academic Roadmap",
    category: "Academic Planning",
    description:
      "Create a personalized CGPA roadmap and learn how to strategically improve your academic performance each semester.",
    instructor: "Prof. Michael Adams",
    instructorRole: "Academic Consultant",
    date: "August 18, 2026",
    time: "2:00 PM",
    duration: "3 Hours",
    location: "Knowledge City Hall",
    mode: "Hybrid",
    image:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    seats: 80,
    enrolled: 65,
    price: "Free",
    level: "Intermediate",
    tags: ["CGPA", "Planning", "University"],
    status: "Open",
    registrationDeadline: "August 16, 2026",
  },
  {
    id: "2",
    title: "Exam Preparation Bootcamp",
    category: "Exam Success",
    description:
      "Prepare effectively for examinations using proven revision methods, mock tests, and confidence-building strategies.",
    instructor: "Grace Williams",
    instructorRole: "Learning Strategist",
    date: "August 25, 2026",
    time: "10:00 AM",
    duration: "4 Hours",
    location: "Zoom",
    mode: "Online",
    image:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80",
    seats: 150,
    enrolled: 143,
    price: "Free",
    level: "Beginner",
    tags: ["Exams", "Revision", "Productivity"],
    status: "Almost Full",
    registrationDeadline: "August 23, 2026",
  },
  {
    id: "3",
    title: "Research Writing & Final Year Projects",
    category: "Research",
    description:
      "Understand how to choose research topics, structure projects, cite references correctly, and avoid plagiarism.",
    instructor: "Dr. Emmanuel Peters",
    instructorRole: "Research Mentor",
    date: "September 2, 2026",
    time: "3:00 PM",
    duration: "2.5 Hours",
    location: "D'roid Training Centre",
    mode: "Physical",
    image:
      "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
    seats: 60,
    enrolled: 28,
    price: "$10",
    level: "Intermediate",
    tags: ["Research", "Projects", "Writing"],
    status: "Open",
    registrationDeadline: "August 31, 2026",
  },
];
