import { MembershipTier } from "./types";

export const TIERS: MembershipTier[] = [
  {
    id: "free",
    name: "Free",
    price: 0,
    badge: "Starter",
    badgeColor: "bg-purple-100 text-purple-700",
    tagline: "Explore the community at no cost.",
    accentColor: "border-purple-950/10",
    cardBg: "bg-white",
    buttonStyle:
      "border border-purple-950/20 text-purple-950 hover:bg-purple-50",
    popular: false,
    features: [
      "Browse all public campaigns",
      "Read community forums",
      "Monthly iLEAD newsletter",
      "Public event announcements",
      "View iTrain previews",
    ],
    locked: [
      "Join & comment on campaigns",
      "Mentorship matching",
      "iShare participation",
      "Certificate of contribution",
      "Priority support",
    ],
  },
  {
    id: "silver",
    name: "Silver",
    price: 2500,
    badge: "Community",
    badgeColor: "bg-slate-100 text-slate-600",
    tagline: "Get active in the iLEAD ecosystem.",
    accentColor: "border-slate-300",
    cardBg: "bg-white",
    buttonStyle: "border border-slate-400 text-slate-700 hover:bg-slate-50",
    popular: false,
    features: [
      "Everything in Free",
      "Join & comment on campaigns",
      "Full community forum access",
      "Basic iTrain content library",
      "Priority email support",
      "Member directory listing",
    ],
    locked: [
      "Mentorship matching",
      "iShare participation",
      "Certificate of contribution",
      "Leadership direct access",
    ],
  },
  {
    id: "gold",
    name: "Gold",
    price: 5000,
    badge: "Most Popular",
    badgeColor: "bg-orange-100 text-orange-700",
    tagline: "Unlock mentorship, sharing, and growth.",
    accentColor: "border-orange-400",
    cardBg: "bg-white",
    buttonStyle:
      "bg-orange-500 hover:bg-orange-600 text-white shadow-md shadow-orange-500/20",
    popular: true,
    features: [
      "Everything in Silver",
      "Mentorship matching (2 sessions/mo)",
      "iShare participation — give & receive",
      "Full iTrain content library",
      "Certificate of contribution",
      "Top Givers leaderboard eligibility",
    ],
    locked: [
      "Unlimited mentorship sessions",
      "Featured profile badge",
      "Direct leadership access",
    ],
  },
  {
    id: "platinum",
    name: "Platinum",
    price: 10000,
    badge: "Premium",
    badgeColor: "bg-purple-950 text-white",
    tagline: "The full iLEAD experience, no limits.",
    accentColor: "border-purple-950",
    cardBg: "bg-white",
    buttonStyle:
      "bg-purple-950 hover:bg-purple-800 text-white shadow-md shadow-purple-950/20",
    popular: false,
    features: [
      "Everything in Gold",
      "Unlimited mentorship sessions",
      "Featured profile & verification badge",
      "Direct access to iLEAD leadership",
      "Early access to new features",
      "Custom community spotlight post",
      "Dedicated account support",
    ],
    locked: [],
  },
];
